name: Deploy App

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  build: 
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.1" -scheme cyfaceapp build
      - name: Test
        run: xcodebuild -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.1" -scheme cyfaceapp test  
