name: Deploy App

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  build_with_signing: 
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install the Apple Certificate and Provisioning Profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create Temporary Keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import Certificate to Keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply Provisioning Profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Test
        run: |
          xcodebuild -scheme cyfaceapp \
          -sdk iphoneos \
          -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.1" \
          test

      - name: Build Archive
        run: |
          xcodebuild -scheme cyfaceapp \
          -archivePath $RUNNER_TEMP/cyfaceapp.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive

# [Klemens Muthmann: 15.10.2024] The following two steps are supposed to create an IPA file for app deployment. However this does not work, since the Provisioning Profile for de.cyface.app can not be found. 
# It is at the documented place with the right content and access rights. I have no idea why this does not work. It works locally on my machine. However it is not necessary to build this here. Since it works locally,
# building the App locally and deploying to the App store should suffice for the moment.
      #- name: Export IPA
      #  env:
      #    EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      #  run: |
      #    ls -alih ~/Library/MobileDevice/Provisioning\ Profiles
      #    EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
      #    echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
      #    cat $EXPORT_OPTS_PATH
      #    xcodebuild -exportArchive -verbose \
      #    -archivePath $RUNNER_TEMP/cyfaceapp.xcarchive \
      #    -exportOptionsPlist $EXPORT_OPTS_PATH \
      #    -exportPath $RUNNER_TEMP/build

      #- name: Upload Application
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: app
      #    path: ${{ runner.temp }}/build/cyfaceapp.ipa
      #    retention-days: 3

